package com.infosense.rules

import com.infosense.ibilling.server.item.db.ItemDTO
import com.infosense.ibilling.server.order.db.OrderLineDTO
import com.infosense.ibilling.server.order.db.OrderDTO
import com.infosense.ibilling.server.user.ContactDTOEx
import com.infosense.ibilling.server.item.tasks.SubscriptionResult
import com.infosense.ibilling.server.order.OrderLineBL
import com.infosense.ibilling.server.order.OrderBL
import com.infosense.ibilling.server.item.tasks.PricingResult
import com.infosense.ibilling.server.user.UserDTOEx
import java.math.BigDecimal
import java.util.List
import org.apache.log4j.Logger

global org.apache.log4j.Logger LOG

rule '祥云A 包月'

dialect 'mvel'

when	
    $order : OrderDTO( )
    OrderLineDTO( itemId == 2333 ) from $order.lines 	
    not( OrderLineDTO( itemId == 2317 ) from $order.lines) 
then
    # add account maintenance fee
    OrderLineBL.addItem($order, 2317)
    OrderLineBL.addItem($order, 2320)
    update($order)	
    LOG.debug("祥云A包月")
    
end

rule '祥云A 包年'

dialect 'mvel'

when
    $order : OrderDTO( )
    OrderLineDTO( itemId == 2334 ) from $order.lines 	
    not( OrderLineDTO( itemId == 2317 ) from $order.lines)
then
    OrderLineBL.addItem($order, 2317)
    OrderLineBL.addItem($order, 2320)
    update($order)
    
end


rule '祥云A 即付即用'

dialect 'mvel'

when
    $order : OrderDTO( )
    OrderLineDTO( itemId == 2400 ) from $order.lines 	
    not( OrderLineDTO( itemId == 2325 ) from $order.lines)
then
    OrderLineBL.addItem($order, 2325)
    OrderLineBL.addItem($order, 2329)
    update($order)

end

